FROM apache/airflow:2.5.0-python3.10

USER airflow

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/mlflow/artifacts && chmod -R 777 /opt/mlflow

# Install everything as root
RUN pip install --no-cache-dir --upgrade mlflow==2.13.0

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
